<?php

define('RECOGNIZED_CITIES','mumbai,bangalore');

define('mumbai_NORTH', '19.23000000');
define('mumbai_SOUTH', 18.90000000);
define('mumbai_EAST', 72.95500000);
define('mumbai_WEST', 72.810000);

define('bangalore_SOUTH', 12.729591);
define('bangalore_NORTH', 13.17951);
define('bangalore_EAST', 77.877816);
define('bangalore_WEST', 77.383402);

define('unrecognized_region_NORTH', 90);
define('unrecognized_region_SOUTH', -90);
define('unrecognized_region_EAST', 180);
define('unrecognized_region_WEST', -180);

define('DEG_STEP', 0.001);
define('RADIUS_X', 112);
define('RADIUS_Y', 105);

define('ENABLE_CACHING',0);
define('CACHE_EXPIRY', 100);


?>
